
AM_CFLAGS =\
         -Wall\
         -g\
	 -DNOJPEG -DNOZLIB -DNOPNG

AM_CXXFLAGS =\
         -Wall\
         -g\
	 -DNOJPEG -DNOZLIB -DNOPNG

noinst_LIBRARIES = libharu.a

libharu_a_SOURCES = \
  libharuc.cc libharuc_cnsfonts.cc libharuc_cntfonts.cc libharuc_jpfonts.cc \
  libharuc_krfonts.cc libharu_jpeg.cc libharu_png.cc PdfAnnotations.cc \
  PdfAutoPtrObjects.cc PdfBorderStyle.cc PdfCatalog.cc PdfCMap.cc \
  PdfCMap_ETen_B5.cc PdfCMap_EUC.cc PdfCMap_GB_EUC.cc PdfCMap_KSC_EUC.cc \
  PdfCMap_KSCms_UHC.cc PdfCMap_RKSJ.cc PdfContents.cc PdfDestinations.cc \
  PdfDoc.cc PdfEncoding.cc PdfEncoding_ISO8859.cc PdfEncoding_KOI8.cc \
  PdfEncoding_MSCP.cc PdfEncrypt.cc PdfExceptions.cc PdfFontDef.cc \
  PdfFontDef_Courier.cc PdfFontDef_Helvetica.cc PdfFontDef_Symbol.cc \
  PdfFontDef_Times.cc PdfFontDef_ZapfDingbats.cc PdfFonts.cc PdfInfo.cc \
  PdfJpegImage.cc PdfList.cc PdfMbFontDef_Batang.cc PdfMbFontDef_Dotum.cc \
  PdfMbFontDef_Gothic.cc PdfMbFontDef_Mincyo.cc PdfMbFontDef_Ming.cc \
  PdfMbFontDef_SimHei.cc PdfMbFontDef_SimSun.cc PdfMbFonts.cc PdfObjects.cc \
  PdfOutlines.cc PdfPages.cc PdfPngImage.cc PdfStreams.cc PdfUnicodeText.cc \
  PdfUtils.cc PdfXObjects.cc PdfXref.cc libharuc_cnsfonts.h \
  libharuc_cntfonts.h libharuc.h libharuc_ISO8859.h libharuc_jpfonts.h \
  libharuc_KOI8.h libharuc_krfonts.h libharuc_MSCP.h libharu_cnsfonts.h \
  libharu_cntfonts.h libharu.h libharu_ISO8859.h libharu_jpfonts.h \
  libharu_KOI8.h libharu_krfonts.h libharu_MSCP.h
