AM_CXXFLAGS =\
         -Wall\
         -g

noinst_LIBRARIES = libncl.a

libncl_a_SOURCES = \
  ncl.h nxsassumptionsblock.cpp nxsassumptionsblock.h nxsblock.cpp nxsblock.h\
  nxscharactersblock.cpp nxscharactersblock.h nxsdatablock.cpp nxsdatablock.h\
  nxsdefs.h nxsdiscretedatum.cpp nxsdiscretedatum.h nxsdiscretematrix.cpp\
  nxsdiscretematrix.h nxsdistancedatum.cpp nxsdistancedatum.h\
  nxsdistancesblock.cpp nxsdistancesblock.h nxsemptyblock.cpp nxsemptyblock.h\
  nxsexception.cpp nxsexception.h nxsindent.h nxsreader.cpp nxsreader.h\
  nxssetreader.cpp nxssetreader.h nxsstring.cpp nxsstring.h nxstaxablock.cpp\
  nxstaxablock.h nxstoken.cpp nxstoken.h nxstreesblock.cpp nxstreesblock.h
